//auth
export const ACCOUNT_SETUP = 'ACCOUNT_SETUP'
export const ACCOUNT_SIGNUP_FAILUR = 'ACCOUNT_SIGNUP_FAILUR'
export const ACCOUNT_UPDATE_FAILUR = 'ACCOUNT_UPDATE_FAILUR'
export const GENERATING_CORPORSTION_INVESTMENT = 'GENERATING_CORPORSTION_INVESTMENT'
export const GENERATE_CORPORSTION_INVESTMENT_FAILUR = 'GENERATE_CORPORSTION_INVESTMENT_FAILUR'
export const GENERATE_CORPORSTION_INVESTMENT_SUCCESS ='GENERATE_CORPORSTION_INVESTMENT_SUCCESS'
export const DELETING_CORPORSTION_INVESTMENT ='DELETING_CORPORSTION_INVESTMENT'
export const DELETE_CORPORSTION_INVESTMENT_FAILUR ='DELETE_CORPORSTION_INVESTMENT_FAILUR'
export const DELETE_CORPORSTION_INVESTMENT_SUCCESS ='DELETE_CORPORSTION_INVESTMENT_SUCCESS'
export const ACCOUNT_LOGOUT_SETUP = 'ACCOUNT_LOGOUT_SETUP'

//transaction
export const TRANSACTION_PRESISTING = 'TRANSACTION_PRESISTING'
export const TRANSACTION_PRESISTED_FAILUR = 'TRANSACTION_PRESISTED_FAILUR'
export const TRANSACTION_PRESISTED_SUCCESS = 'TRANSACTION_PRESISTED_SUCCESS'

//corporations
export const LOADING_CORPORATIONS = 'LOADING_CORPORATIONS'
export const FETCH_CORPORATIONS = 'FETCH_CORPORATIONS'

//currencies
export const LOADING_CURRENCIES ='LOADING_CURRENCIES'
export const FETCH_CURRENCIES = 'FETCH_CURRENCIES'

export const LOADING_INVESTMENTS = 'LOADING_INVESTMENTS'
export const FETCH_INVESTMENTS = 'FETCH_INVESTMENTS'

//sessions
export const LOGIN_LOADING ='LOGIN_LOADING'
export const LOGIN_FAILUR ='LOGIN_FAILUR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS'